spring:
  datasource:
    //TODO GTB：需要添加"driver-class-name: com.mysql.jdbc.Driver"
    url: jdbc:mysql://localhost:3306/final?characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
//TODO GTB: 这里使用create合适吗？
